overwrite: true
schema: "http://localhost:4000"
documents:
  - "./pages/**/*.(tsx|ts)"
generates:
  __generated__/graphql-operations.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
      # - typescript-react-apollo
      # - typescript-document-nodes
  # ./graphql.schema.json:
  #   plugins:
  #     - "introspection"
  __generated__/gql/:
    preset: gql-tag-operations-preset
  __generated__/apollo-helpers.ts:
    plugins:
      - typescript-apollo-client-helpers
