import Head from "next/head";
import { gql } from "__generated__/gql";
import { NextPage, GetServerSideProps } from "next";
import { useSuspenseQuery } from "@apollo/client";

const GetProductDocument = gql(`
  query GetProduct ($id: ID!) {
    product(id: $id) {
      id
      name
      description
      price
    }
  }
`);

interface IProductProps {
  id: string;
}

const Product: NextPage<IProductProps> = ({ id }) => {
  const { data, error } = useSuspenseQuery(GetProductDocument, {
    variables: {
      id,
    },
    returnPartialData: true,
    partialRefetch: true, // TODO: Test what this does
  });

  if (!data) {
    return null;
  }

  console.log({ product: data.product });

  return (
    <div>
      <Head>
        <title>{data.product?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{data.product?.name}</h1>

        <p>Price: {data.product?.price}</p>

        <p>{data.product?.description}</p>
      </main>
    </div>
  );
};

export default Product;

export const getServerSideProps: GetServerSideProps<IProductProps> = async ({
  query,
}) => {
  if (!query.id || Array.isArray(query.id)) {
    throw new Error("Parameter `id` is not in the correct format");
  }
  return {
    props: {
      id: query.id,
    },
  };
};
